//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlataformaDKUCorp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archivo
    {
        public int archivoID { get; set; }
        public string archivoNom { get; set; }
        public string nomReal { get; set; }
        public string bajoMaestro { get; set; }
        public byte[] contenido { get; set; }
    
        public virtual Maestro Maestro { get; set; }
    }
}
